#!/usr/bin/python3

import requests

ITEMURL = "http://pokeapi.co/api/v2/item/"


def main():
    items_request = requests.get(f"{ITEMURL}?limit=1000")
    items = items_request.json()


    heals = []

    for item in items.get("results"):
        if 'heal' in items.get("name"):
            heals.append(item.get("name"))

    print(f"There are {len(heals)} words that contain the word 'heal' in the Pokemon Item API")
    print("List of Pokemon items containing heal:")
    print(heals)

if __name__ == "__main__":
    main()
